apiVersion: v2
name: people-api
description: A Helm chart for deploying a Spring Boot application with PostgreSQL database connectivity
type: application
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - name: Yves Kaufmann
    url: https://github.com/yagan93
keywords:
  - spring-boot
  - postgresql